[project]
name = 'Blockchain-Based-Research-Project-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.progress-tracking]
path = 'contracts/progress-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.project-coordination]
path = 'contracts/project-coordination.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
